- libs/stack-ui/.storybook/preview.js
- libs/stack-ui/src/components/Date/date.stories.mdx
- libs/stack-ui/src/components/Date/index.tsx
- libs/stack-ui/src/components/Date/interface.ts
> STACK-15 Date Component Formatter Options extension

- libs/stack-ui/src/providers/Theme/hooks.ts
https://okamca.atlassian.net/browse/STACK-21
Build stack-ui
> fix: return value of useThemeContext can be either string of undefined

- libs/stack-ui/src/components/fields/TextArea/index.tsx
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/STACK-28
Storybook
> STACK-28-Component-TextArea-should-have-both-a-wrapper-and-a-container

- libs/stack-ui/src/index.ts
https://okamca.atlassian.net/browse/STACK-29
> STACK-29-BoxWithForwardRef-doesn-t-get-exported 

- libs/stack-ui/src/components/Popover/index.tsx
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/STACK-43
Storybook popover component should have a gray background
> Stack 43 component popover s popover is unstylable

- libs/stack-ui/src/components/ShareButton/index.tsx
- libs/stack-ui/src/storybook/ShareButtonExample/index.tsx
This task has already been done in the context of The Lede
https://github.com/OKAMca/bellmedia-thelede-nextjs/pull/73
The linked task has been resolved in this PR : https://okamca.atlassian.net/jira/software/projects/STACK/issues/STACK-44
> STACK 46 share button reformat

- libs/stack-ui/src/components/Popover/index.tsx
https://okamca.atlassian.net/browse/STACK-50
Check that the element the popover button creates has the same `id` as its `aria-controls` value
> STACK-50-Component-Popover-is-missing-aria-controls

- libs/stack/stack-ui/src/components/Accordion/accordion.stories.mdx
- libs/stack/stack-ui/src/components/Accordion/index.tsx
- libs/stack/stack-ui/src/components/Accordion/interface.ts
https://okamca.atlassian.net/browse/STACK-104
> Stack 104 accordion should take component icon have a default opened state prop

- .github/workflows/publishing.yml
- libs/directus/directus-node/package.json
- package.json
Missing .mjs output like the other package, but vite is not used in this package?
> chore(directus-node): try to publish the package

- libs/stack/stack-ui/src/components/fields/TextInputField/index.tsx
- libs/stack/stack-ui/src/components/fields/TextInputField/interface.ts
Note that the type is TextFieldAria<'input'>['inputProps'] (converted as "never") because of `ReactDOM[K] extends DOMFactory<infer T, any> ? T : never;`  (from react)
But the online documentation specified inputProps as InputHTMLAttributes<HTMLInputElement>  where InputHTMLAttributes is from react and HTMLInputElement from global (dom)
> fix(textinputfield): adding inputProps type casting

- libs/stack/stack-ui/src/components/WysiwygBlock/index.tsx
- libs/stack/stack-ui/src/components/WysiwygBlock/wysiwyg.stories.mdx
https://okamca.atlassian.net/browse/STACK-142
- You can test this PR by running the `yarn storybook` CLI command and you should see the `Wysiwyg block` story under `Base Components`
> refactor: add target link attribute to wysiwyg

- libs/stack/stack-ui/src/components/Accordion/accordion.stories.mdx
- libs/stack/stack-ui/src/components/Accordion/components/AriaAccordionItem.tsx
- libs/stack/stack-ui/src/components/Accordion/interface.ts
- libs/stack/stack-ui/src/theme/Accordion/index.tsx
https://okamca.atlassian.net/browse/STACK-143
- Storybook
- Some accordion stories should have custom accordion items tokens
> fix: Stack-143 accordion accordion items can t define their own

- libs/stack/stack-ui/src/components/Accordion/components/AriaAccordionItem.tsx
https://okamca.atlassian.net/browse/STACK-158
- Try in storybook to open multiple items and look if the attributes follow correctly
> fix: aria expanded attributes not set properly on multiple items accordions

- libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
- libs/stack/stack-ui/src/components/Alerts/interface.ts
- libs/stack/stack-ui/src/theme/Alerts/index.ts
https://okamca.atlassian.net/browse/STACK-159
- Test Focus on slides
To handle ordering some CSS had to be added, might impact other projects
> fix: alerts a11y focus carousel

- libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
- libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPagination.tsx
- libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPaginationBullet.tsx
- libs/stack/stack-ui/src/components/Alerts/interface.ts
- libs/stack/stack-ui/src/theme/Alerts/index.ts
- package.json
- yarn.lock
https://okamca.atlassian.net/browse/STACK-160
- Check if all a11y features are present for pagination since I needed to remake this feature from scratch
> fix: a11y on pagination for alerts

- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
https://okamca.atlassian.net/browse/STACK-160
Previous PR introduced a bug by adding a wrapper div for the alert item content
> fix: alert slide theme

- libs/directus/directus-block/README.md
https://github.com/OKAMca/cepsum-mono/blob/CEP-156-Brand-ui-Alerts/libs/ui/src/components/Alerts/components/AlertsNextButton.tsx
> docs: clearer blocks dispatcher doc, include blocks prop

- libs/stack/stack-ui/src/components/DirectusImg/index.tsx
- libs/stack/stack-ui/src/components/DirectusImg/interface.ts
https://okamca.atlassian.net/browse/STACK-180
> Stack 180 directus image add an option for passing the image domain

- libs/directus/directus-flexible-content/package.json
> chore(release): flexible content access to public

- libs/directus/directus-block/package.json
- libs/directus/directus-block/vite.config.ts
> fix(directus-block): export server components

- libs/directus/directus-node/package.json
https://okamca.atlassian.net/browse/CEP-217
- after publishing, require of @okam/directus-node should work
> fix(directus-node): fix package.json with published structured reference

- libs/stack/stack-ui/src/components/DirectusImg/index.tsx
- libs/stack/stack-ui/src/components/DirectusImg/interface.ts
Sometimes we need images pointing to http, not https. This allows to change the protocol to http
> fix: allow changing directus img protocol

- libs/directus/directus-flexible-content/src/index.ts
- libs/directus/directus-flexible-content/src/lib/components/nodes/types.ts
- libs/directus/directus-flexible-content/vite.config.ts
- package-lock.json
add stack-ui and directus block to external deps
> fix(directus-flexible-content): add stack-ui and directus block to external deps

- apps/demo/app/flexible-editor/page.tsx
- libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
- libs/directus/directus-flexible-content/src/lib/functions/injectDataIntoContent.ts
> fix(directus-flexible-editor): fixed content injection and prop name

- libs/directus/directus-flexible-content/README.md
https://okamca.atlassian.net/browse/STACK-181
https://github.com/OKAMca/stack/tree/stack-181-flexible-editor-doc/libs/directus/directus-flexible-content
> docs(directus-flexible-content): add documentation

- apps/demo/app/directus-next-component/directus-link/page.tsx
- libs/directus/directus-next-component/README.md
- libs/directus/directus-next-component/src/components/DirectusLink/index.tsx
- libs/directus/directus-next-component/src/components/DirectusLink/interface.ts
- libs/directus/directus-next-component/src/hooks/directus-link.ts
- libs/directus/directus-next-component/src/hooks/navigation-items.tsx
- libs/directus/directus-next-component/src/index.ts
https://okamca.atlassian.net/browse/STACK-189
- /directus-next-component/directus-link
> STACK-189-DirectusLink-Accessibility-props-other-fixes

- libs/directus/directus-block/src/server.ts
- libs/directus/directus-block/vite.config.ts
https://okamca.atlassian.net/browse/STACK-201
- build directus-block
> STACK-201-Stop-directus-block-from-building-within-itself

- libs/directus/directus-next-component/src/hooks/directus-link.ts
https://okamca.atlassian.net/browse/STACK-203
- /directus-next-component/directus-link
- All links should render correctly
> STACK-203-Directus-links-of-type-file-should-return-valid-href

- .gitignore
- libs/directus/directus-node/src/lib/redirection.ts
- Logging to display how many redirects and rewrite were added.
- Log if there is an error but still return true so that build doesn't fail in CI and deployments
> Log redirects
