- libs/stack-ui/src/components/Icon/index.tsx
> Icons Lazy import fix

- libs/stack-ui/src/index.ts
> feat: added useThemeContext to exports

- libs/stack-ui/src/components/Calendar/RangeCalendar.tsx
- libs/stack-ui/src/components/Calendar/calendar.stories.mdx
- libs/stack-ui/src/components/Calendar/components/CalendarCell.tsx
- libs/stack-ui/src/components/Calendar/components/CalendarGrid.tsx
- libs/stack-ui/src/components/Calendar/index.tsx
- libs/stack-ui/src/components/Calendar/interface.ts
- libs/stack-ui/src/components/DatePicker/DateRangePicker.tsx
- libs/stack-ui/src/components/DatePicker/components/CalendarPopover.tsx
- libs/stack-ui/src/components/DatePicker/components/DateField.tsx
- libs/stack-ui/src/components/DatePicker/date-picker.stories.mdx
- libs/stack-ui/src/components/DatePicker/index.tsx
- libs/stack-ui/src/components/DatePicker/interface.ts
- libs/stack-ui/src/components/Dialog/index.tsx
- libs/stack-ui/src/components/Dialog/interface.ts
- libs/stack-ui/src/providers/Theme/utils.ts
- libs/stack-ui/src/theme/Calendar/index.tsx
- libs/stack-ui/src/theme/DatePicker/index.tsx
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/START-12
Storybook
> feat: Calendar / Date Picker Components (With Ranged as well)

- libs/stack-ui/src/index.ts
https://okamca.atlassian.net/browse/STACK-18
> feat: added date to exports

- libs/stack-ui/src/components/Lightbox/index.tsx
- libs/stack-ui/src/components/Lightbox/interface.ts
- libs/stack-ui/src/components/Lightbox/lightbox.stories.mdx
- libs/stack-ui/src/theme/LightBox/index.ts
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/STACK-19
> fix: changed hardcoded open dialog to prop

- libs/stack-ui/src/components/fields/Select/Select.interface.ts
- libs/stack-ui/src/components/fields/Select/Select.stories.mdx
- libs/stack-ui/src/components/fields/Select/Select.tsx
- libs/stack-ui/src/storybook/SelectField/index.tsx
https://okamca.atlassian.net/browse/STACK-23
Storybook
> fix: onChange, manual select value modifs, button tokens

- package.json
- yarn.lock
https://okamca.atlassian.net/browse/STACK-35
> STACK-35-Upgrade-react-types-shared

- libs/stack-ui/src/components/fields/Select/Select.tsx
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/P125-322
- Open Select component
- Notice new spacing betweens items and color on hover
> STACK-38-Component-Select-ul-and-li-are-unstylable

- package.json
- yarn.lock
https://okamca.atlassian.net/browse/STACK-40
Change the locale of the I18nProvider in storybook to fr-CA to see the dates changing language
> STACK-40-Packages-React-aria-update

- libs/stack-ui/src/components/fields/Select/Select.interface.ts
- libs/stack-ui/src/components/fields/Select/Select.stories.mdx
- libs/stack-ui/src/components/fields/Select/Select.tsx
- libs/stack-ui/src/storybook/SelectField/index.tsx
https://okamca.atlassian.net/browse/STACK-41
Storybook (see one of Select variant has different icon)
> STACK-41-Component-Select-icon-is-hard-coded

- libs/stack-ui/src/components/Button/index.tsx
- libs/stack-ui/src/components/Lightbox/index.tsx
- libs/stack-ui/src/components/Modal/Dialog.tsx
- libs/stack-ui/src/components/Popover/index.tsx
- libs/stack-ui/src/components/Popover/interface.ts
- libs/stack-ui/src/components/Popover/popover.stories.mdx
- libs/stack-ui/src/components/ShareButton/index.tsx
- libs/stack-ui/src/components/ShareButton/interface.ts
- libs/stack-ui/src/components/ShareButton/share-button.stories.mdx
- libs/stack-ui/src/components/fields/DatePicker/components/DateField.tsx
- libs/stack-ui/src/components/fields/Select/components/Listbox.tsx
- libs/stack-ui/src/components/fields/TextArea/index.tsx
- libs/stack-ui/src/components/fields/TextArea/textArea.stories.mdx
- libs/stack-ui/src/components/fields/TextInputField/index.tsx
- libs/stack-ui/src/theme/Accordion/index.tsx
- libs/stack-ui/src/theme/Button/index.tsx
- libs/stack-ui/src/theme/Calendar/index.tsx
- libs/stack-ui/src/theme/DatePicker/index.tsx
- libs/stack-ui/src/theme/LightBox/index.ts
- libs/stack-ui/src/theme/ShareButton/index.tsx
- libs/stack-ui/src/theme/TextArea/index.ts
- libs/stack-ui/src/theme/index.tsx
- libs/stack-ui/tailwind.config.js
- package.json
- tailwind.preset.js
- yarn.lock
https://okamca.atlassian.net/browse/STACK-32
Components' outline should only appear on keyboard focus, not on mouse focus
Storybook
> Stack 32 focus on clickable elements

- libs/stack-ui/src/components/fields/Checkbox/Checkbox.interface.ts
- libs/stack-ui/src/components/fields/Checkbox/Checkbox.stories.mdx
- libs/stack-ui/src/components/fields/Checkbox/index.tsx
- libs/stack-ui/src/components/icons/Check.tsx
- libs/stack-ui/src/theme/Checkbox/index.ts
- libs/stack-ui/src/theme/index.tsx
https://okamca.atlassian.net/browse/STACK-45
Storybook
> Stack 45 component checkbox accessibility and icon

- libs/stack-ui/src/components/fields/Select/Select.tsx
- libs/stack-ui/src/components/fields/Select/components/Popover.tsx
https://okamca.atlassian.net/browse/STACK-54
Make sure no console errors/warnings remain on the select component (opened & closed)
> STACK-54-Component-Select-Unknown-event-handlers

- libs/stack-ui/src/components/fields/Checkbox/Checkbox.interface.ts
- libs/stack-ui/src/components/fields/Checkbox/Checkbox.stories.mdx
https://okamca.atlassian.net/browse/STACK-56
Make sure the "Check from other component" checkbox component story makes the user able to check the checkbox by clicking on the button
> STACK-56-Component-Checkbox-Use-react-aria-types

- libs/stack-ui/src/components/Popover/index.tsx
- libs/stack-ui/src/components/Popover/interface.ts
- libs/stack-ui/src/components/Popover/popover.stories.mdx
https://okamca.atlassian.net/browse/STACK-60
See the difference between the two popover storybook examples
> STACK-60-Component-Popover-Clicking-outside-should-close-the-popover

- libs/stack-ui/src/components/fields/Select/Select.tsx
https://okamca.atlassian.net/browse/STACK-66
Storybook
> STACK-66-Component-Select-is-uninteractable-on-mobile

- libs/stack-ui/src/components/fields/Checkbox/Checkbox.interface.ts
- libs/stack-ui/src/components/fields/CheckboxGroup/checkbox-group.stories.mdx
- libs/stack-ui/src/components/fields/CheckboxGroup/components/CheckboxGroupItem/index.tsx
- libs/stack-ui/src/components/fields/CheckboxGroup/index.tsx
- libs/stack-ui/src/components/fields/CheckboxGroup/interface.ts
- libs/stack-ui/src/providers/CheckboxGroup/index.tsx
- libs/stack-ui/src/providers/CheckboxGroup/interface.ts
- libs/stack-ui/src/theme/CheckboxGroup/index.ts
- libs/stack-ui/src/theme/index.tsx
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/
https://react-spectrum.adobe.com/react-aria/useCheckboxGroup.html
> STACK-68-Component-CheckboxGroup

- libs/stack/stack-ui/src/components/Menu/components/MenuItems.tsx
https://okamca.atlassian.net/browse/STACK-94
> STACK-94-Menu-Individual-menu-items-should-render-their-individual-tokens

- libs/stack/stack-ui/src/components/Menu/components/MenuItems.tsx
https://okamca.atlassian.net/browse/STACK-102
> STACK-102-Menu-Childitems-is-not-a-valid-react-prop

- libs/stack/stack-ui/.storybook/main.ts
- package.json
- yarn.lock
https://okamca.atlassian.net/browse/STACK-111
Storybook
> STACK-111-Install-storybook-addon-a11y

- libs/directus/directus-node/README.md
- libs/directus/directus-node/package.json
minor update, wait for more update
> P125 544 fix directus node readme

- libs/stack/stack-ui/src/components/fields/CheckboxGroup/index.tsx
- libs/stack/stack-ui/src/providers/CheckboxGroup/index.tsx
- libs/stack/stack-ui/src/providers/CheckboxGroup/interface.ts
- yarn.lock
https://okamca.atlassian.net/browse/STACK-133
- Storybook
- Checkbox group should render normally
> fix: checkbox group should pass the state to its provider

- apps/demo/app/page.tsx
- libs/stack/stack-ui/src/components/fields/Select/Select.interface.ts
- libs/stack/stack-ui/src/components/fields/Select/Select.tsx
- libs/stack/stack-ui/src/components/fields/SelectItem/SelectItem.interface.ts
- libs/stack/stack-ui/src/components/fields/SelectItem/SelectItem.tsx
- libs/stack/stack-ui/src/storybook/SelectField/index.tsx
> fix: select do not work on in nextjs app

- libs/stack/stack-ui/src/components/Alerts/alerts.stories.mdx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsCloseButton.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsNavigationButton.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
- libs/stack/stack-ui/src/components/Alerts/index.tsx
- libs/stack/stack-ui/src/components/Alerts/interface.ts
- libs/stack/stack-ui/src/components/Lightbox/hooks/overlay/index.tsx
- libs/stack/stack-ui/src/components/Lightbox/index.tsx
- libs/stack/stack-ui/src/components/Lightbox/interface.ts
- libs/stack/stack-ui/src/components/Modal/interface.ts
- libs/stack/stack-ui/src/index.ts
- libs/stack/stack-ui/src/theme/Alerts/index.ts
- libs/stack/stack-ui/src/theme/index.tsx
- libs/stack/stack-ui/src/transitions/RenderWithOpacity.tsx
- libs/stack/stack-ui/src/types/components.ts
- yarn.lock
https://okamca.atlassian.net/browse/STACK-150
- Should the component support pagination and/or other react swiper features or do we want this to always be a carousel with next/prev buttons?
- Storybook
> STACK-150-Component-Alerts

- libs/stack/stack-ui/src/index.ts
> add export for dateRangePicker

- libs/stack/stack-ui/src/index.ts
> export search provider

- libs/directus/directus-block/src/components/BlockDispatcher/config.ts
- libs/directus/directus-block/src/components/BlockDispatcher/index.tsx
- libs/directus/directus-block/src/components/BlockSerializer/interface.ts
- libs/directus/directus-block/src/index.ts
https://okamca.atlassian.net/browse/STACK-162
> refactor: add missing exports

- apps/demo/app/components/example.tsx
- apps/demo/app/query-example.tsx
- libs/directus/directus-query/README.md
- libs/directus/directus-query/src/index.ts
- libs/directus/directus-query/src/lib/init.ts
- libs/directus/directus-query/src/server.ts
> fix(directus-query): fix initDirectusQuery name

- libs/directus/directus-next-component/README.md
- Update the README.md of directus-next-component
> chore: update directus-next-component readme

- libs/directus/directus-next/.eslintrc.js
- libs/directus/directus-next/README.md
- libs/directus/directus-next/package.json
- libs/directus/directus-next/project.json
- libs/directus/directus-next/tsconfig.json
- libs/directus/directus-next/tsconfig.lib.json
- libs/directus/directus-next/vite.config.ts
- tsconfig.base.json
> chore: create directus-next lib

- apps/demo/app/directus-block/page.tsx
- libs/directus/directus-block/src/blocks/BlockWysiwyg/index.tsx
- libs/directus/directus-block/src/components/BlockDispatcher/index.tsx
- libs/directus/directus-block/src/utils/get-block-props.ts
- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/index.tsx
- libs/stack/stack-ui/src/components/Carousel/index.tsx
- libs/stack/stack-ui/src/components/fields/DatePicker/DateRangePicker.tsx
- libs/stack/stack-ui/src/components/fields/SearchField/index.tsx
- package.json
- yarn.lock
https://okamca.atlassian.net/browse/STACK-164
- yarn dev
- /directus-block
> Stack 164 directus block manage server client side

- libs/stack/stack-ui/src/components/Alerts/components/AlertsItem.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsNavigationButton.tsx
- libs/stack/stack-ui/src/components/Alerts/components/AlertsSwiper.tsx
- libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPagination.tsx
- libs/stack/stack-ui/src/components/Alerts/components/pagination/AlertsPaginationBullet.tsx
- libs/stack/stack-ui/src/components/Alerts/interface.ts
- libs/stack/stack-ui/src/providers/Alerts/index.tsx
- libs/stack/stack-ui/src/providers/Alerts/interface.ts
- libs/stack/stack-ui/src/theme/Alerts/index.ts
https://okamca.atlassian.net/browse/STACK-160
> fix: alerts semantic html to theme components

- .github/workflows/publish.yml
> chore(release): fix npm token var name

- libs/directus/directus-flexible-content/project.json
> chore(release): flexible-content directory build

- libs/stack/stack-ui/vite.config.ts
- package-lock.json
- package.json
> test: with rollup plugin preserve directives

- libs/stack/stack-ui/src/components/DirectusImg/index.tsx
- libs/stack/stack-ui/src/components/DirectusImg/interface.ts
https://okamca.atlassian.net/browse/CEP-463
> Cep 463 directus image focal point

- libs/directus/directus-flexible-content/src/lib/components/FlexibleEditorContent/index.tsx
- libs/directus/directus-flexible-content/src/lib/components/RenderNodes/index.tsx
> fix(directus-flexible-content): build fix

- README.md
- apps/demo/README.md
None
- Read and test instruction
> docs: adding readme for .env file

- libs/stack/stack-ui/src/components/Carousel/components/CarouselNavigationButton.tsx
> fix: missing use client on carousel nav button

- libs/directus/directus-next/vite.config.ts
- package-lock.json
> fix(directus-next): update build dependencies, exclude next

- README.md
- libs/directus/directus-next/package.json
- package-lock.json
[STACK-148](https://okamca.atlassian.net/browse/STACK-148)
- https://www.npmjs.com/package/@okam/directus-next?activeTab=versions
[STACK-148]: https://okamca.atlassian.net/browse/STACK-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(directus-next): make package public

- .husky/commit-msg
- .husky/pre-commit
> fix: remove yarn

- README.md
- libs/directus/directus-block/package.json
- libs/directus/directus-flexible-content/package.json
- libs/directus/directus-lib/package.json
- libs/directus/directus-next-component/package.json
- libs/directus/directus-node/package.json
- libs/directus/directus-query/package.json
- libs/stack/core-lib/package.json
- libs/stack/logger/package.json
- libs/stack/next-component/package.json
- libs/stack/stack-ui/package.json
> chore: adding repository.url in package.json, removing publishConfig

- libs/directus/directus-query/CHANGELOG.md
- libs/directus/directus-query/package.json
> chore(release): publish

- libs/directus/directus-next/CHANGELOG.md
- libs/directus/directus-next/package.json
- libs/directus/directus-next/src/lib/directusRouteRouter.ts
> Fix directus next release
